name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

  # 默认使用仓库名作为镜像名称
  IMAGE_NAME: dddocr

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      # 增加可用磁盘空间
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:

          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'
          # 如果空间还是不够用，可以把以下开启，清理出更多空间
          # remove-android: 'true'
          # remove-codeql: 'true'
          build-mount-path: '/var/lib/docker/'

      - name: Restart docker
        run: sudo service docker restart

      - name: Free up disk space complete
        run: |
          echo "Free up disk space complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: 获取版本号
        id: version
        run: echo "VERSION=$(date +%Y%m%d)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: 设置镜像名称
        id: image
        run: |
          # 如果设置了自定义镜像名称则使用，否则使用默认值（仓库名）
          echo "NAME=${IMAGE_NAME_OVERRIDE:-$IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push image Aliyun
        run: |
          docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
          name=${IMAGE_NAME_OVERRIDE:-$IMAGE_NAME}
          version=$(date +%Y%m%d)-${GITHUB_SHA::8}
          image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$name:latest"
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$name$version"
          docker build . --file .dockerfile --tag $image
          echo "docker tag $image $new_image"
          docker tag $image $new_image
          echo "docker push $new_image"
          docker push $new_image
          echo "开始清理磁盘空间"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="
          docker rmi $image
          docker rmi $new_image
          echo "磁盘空间清理完毕"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="     
          
          done < images.txt